// Code generated by MockGen. DO NOT EDIT.
// Source: constructor.go
//
// Generated by this command:
//
//	mockgen -source=constructor.go -destination=mock/constructormock.go
//

// Package mock_itinerary is a generated GoMock package.
package mock_itinerary

import (
	reflect "reflect"

	gps "github.com/victorguarana/vehicle-routing/src/gps"
	itinerary "github.com/victorguarana/vehicle-routing/src/itinerary"
	route "github.com/victorguarana/vehicle-routing/src/route"
	slc "github.com/victorguarana/vehicle-routing/src/slc"
	gomock "go.uber.org/mock/gomock"
)

// MockConstructor is a mock of Constructor interface.
type MockConstructor struct {
	ctrl     *gomock.Controller
	recorder *MockConstructorMockRecorder
}

// MockConstructorMockRecorder is the mock recorder for MockConstructor.
type MockConstructorMockRecorder struct {
	mock *MockConstructor
}

// NewMockConstructor creates a new mock instance.
func NewMockConstructor(ctrl *gomock.Controller) *MockConstructor {
	mock := &MockConstructor{ctrl: ctrl}
	mock.recorder = &MockConstructorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConstructor) EXPECT() *MockConstructorMockRecorder {
	return m.recorder
}

// ActualCarPoint mocks base method.
func (m *MockConstructor) ActualCarPoint() gps.Point {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActualCarPoint")
	ret0, _ := ret[0].(gps.Point)
	return ret0
}

// ActualCarPoint indicates an expected call of ActualCarPoint.
func (mr *MockConstructorMockRecorder) ActualCarPoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActualCarPoint", reflect.TypeOf((*MockConstructor)(nil).ActualCarPoint))
}

// ActualCarStop mocks base method.
func (m *MockConstructor) ActualCarStop() route.IMainStop {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActualCarStop")
	ret0, _ := ret[0].(route.IMainStop)
	return ret0
}

// ActualCarStop indicates an expected call of ActualCarStop.
func (mr *MockConstructorMockRecorder) ActualCarStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActualCarStop", reflect.TypeOf((*MockConstructor)(nil).ActualCarStop))
}

// CarEfficiency mocks base method.
func (m *MockConstructor) CarEfficiency() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CarEfficiency")
	ret0, _ := ret[0].(float64)
	return ret0
}

// CarEfficiency indicates an expected call of CarEfficiency.
func (mr *MockConstructorMockRecorder) CarEfficiency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CarEfficiency", reflect.TypeOf((*MockConstructor)(nil).CarEfficiency))
}

// CarSpeed mocks base method.
func (m *MockConstructor) CarSpeed() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CarSpeed")
	ret0, _ := ret[0].(float64)
	return ret0
}

// CarSpeed indicates an expected call of CarSpeed.
func (mr *MockConstructorMockRecorder) CarSpeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CarSpeed", reflect.TypeOf((*MockConstructor)(nil).CarSpeed))
}

// CarSupport mocks base method.
func (m *MockConstructor) CarSupport(nextPoints ...gps.Point) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range nextPoints {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CarSupport", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CarSupport indicates an expected call of CarSupport.
func (mr *MockConstructorMockRecorder) CarSupport(nextPoints ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CarSupport", reflect.TypeOf((*MockConstructor)(nil).CarSupport), nextPoints...)
}

// DroneCanReach mocks base method.
func (m *MockConstructor) DroneCanReach(droneNumber itinerary.DroneNumber, nextPoints ...gps.Point) bool {
	m.ctrl.T.Helper()
	varargs := []any{droneNumber}
	for _, a := range nextPoints {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DroneCanReach", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DroneCanReach indicates an expected call of DroneCanReach.
func (mr *MockConstructorMockRecorder) DroneCanReach(droneNumber any, nextPoints ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{droneNumber}, nextPoints...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DroneCanReach", reflect.TypeOf((*MockConstructor)(nil).DroneCanReach), varargs...)
}

// DroneEfficiency mocks base method.
func (m *MockConstructor) DroneEfficiency() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DroneEfficiency")
	ret0, _ := ret[0].(float64)
	return ret0
}

// DroneEfficiency indicates an expected call of DroneEfficiency.
func (mr *MockConstructorMockRecorder) DroneEfficiency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DroneEfficiency", reflect.TypeOf((*MockConstructor)(nil).DroneEfficiency))
}

// DroneIsFlying mocks base method.
func (m *MockConstructor) DroneIsFlying(droneNumber itinerary.DroneNumber) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DroneIsFlying", droneNumber)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DroneIsFlying indicates an expected call of DroneIsFlying.
func (mr *MockConstructorMockRecorder) DroneIsFlying(droneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DroneIsFlying", reflect.TypeOf((*MockConstructor)(nil).DroneIsFlying), droneNumber)
}

// DroneNumbers mocks base method.
func (m *MockConstructor) DroneNumbers() []itinerary.DroneNumber {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DroneNumbers")
	ret0, _ := ret[0].([]itinerary.DroneNumber)
	return ret0
}

// DroneNumbers indicates an expected call of DroneNumbers.
func (mr *MockConstructorMockRecorder) DroneNumbers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DroneNumbers", reflect.TypeOf((*MockConstructor)(nil).DroneNumbers))
}

// DroneSpeed mocks base method.
func (m *MockConstructor) DroneSpeed() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DroneSpeed")
	ret0, _ := ret[0].(float64)
	return ret0
}

// DroneSpeed indicates an expected call of DroneSpeed.
func (mr *MockConstructorMockRecorder) DroneSpeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DroneSpeed", reflect.TypeOf((*MockConstructor)(nil).DroneSpeed))
}

// DroneSupport mocks base method.
func (m *MockConstructor) DroneSupport(droneNumber itinerary.DroneNumber, deliveryPoint, landingPoint gps.Point) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DroneSupport", droneNumber, deliveryPoint, landingPoint)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DroneSupport indicates an expected call of DroneSupport.
func (mr *MockConstructorMockRecorder) DroneSupport(droneNumber, deliveryPoint, landingPoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DroneSupport", reflect.TypeOf((*MockConstructor)(nil).DroneSupport), droneNumber, deliveryPoint, landingPoint)
}

// LandAllDrones mocks base method.
func (m *MockConstructor) LandAllDrones(landingStop route.IMainStop) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LandAllDrones", landingStop)
}

// LandAllDrones indicates an expected call of LandAllDrones.
func (mr *MockConstructorMockRecorder) LandAllDrones(landingStop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LandAllDrones", reflect.TypeOf((*MockConstructor)(nil).LandAllDrones), landingStop)
}

// LandDrone mocks base method.
func (m *MockConstructor) LandDrone(droneNumber itinerary.DroneNumber, destination route.IMainStop) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LandDrone", droneNumber, destination)
}

// LandDrone indicates an expected call of LandDrone.
func (mr *MockConstructorMockRecorder) LandDrone(droneNumber, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LandDrone", reflect.TypeOf((*MockConstructor)(nil).LandDrone), droneNumber, destination)
}

// MoveCar mocks base method.
func (m *MockConstructor) MoveCar(destination gps.Point) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MoveCar", destination)
}

// MoveCar indicates an expected call of MoveCar.
func (mr *MockConstructorMockRecorder) MoveCar(destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCar", reflect.TypeOf((*MockConstructor)(nil).MoveCar), destination)
}

// MoveDrone mocks base method.
func (m *MockConstructor) MoveDrone(droneNumber itinerary.DroneNumber, destination gps.Point) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MoveDrone", droneNumber, destination)
}

// MoveDrone indicates an expected call of MoveDrone.
func (mr *MockConstructorMockRecorder) MoveDrone(droneNumber, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveDrone", reflect.TypeOf((*MockConstructor)(nil).MoveDrone), droneNumber, destination)
}

// RouteIterator mocks base method.
func (m *MockConstructor) RouteIterator() slc.Iterator[route.IMainStop] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteIterator")
	ret0, _ := ret[0].(slc.Iterator[route.IMainStop])
	return ret0
}

// RouteIterator indicates an expected call of RouteIterator.
func (mr *MockConstructorMockRecorder) RouteIterator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteIterator", reflect.TypeOf((*MockConstructor)(nil).RouteIterator))
}

// StartDroneFlight mocks base method.
func (m *MockConstructor) StartDroneFlight(droneNumber itinerary.DroneNumber, startingPoint route.IMainStop) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartDroneFlight", droneNumber, startingPoint)
}

// StartDroneFlight indicates an expected call of StartDroneFlight.
func (mr *MockConstructorMockRecorder) StartDroneFlight(droneNumber, startingPoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDroneFlight", reflect.TypeOf((*MockConstructor)(nil).StartDroneFlight), droneNumber, startingPoint)
}

// SubItineraryList mocks base method.
func (m *MockConstructor) SubItineraryList() []itinerary.SubItinerary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubItineraryList")
	ret0, _ := ret[0].([]itinerary.SubItinerary)
	return ret0
}

// SubItineraryList indicates an expected call of SubItineraryList.
func (mr *MockConstructorMockRecorder) SubItineraryList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubItineraryList", reflect.TypeOf((*MockConstructor)(nil).SubItineraryList))
}
